//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Services
{
    using System;
    using System.Collections.Generic;
    

    using CRM.IServices;
    using CRM.IRepository;
    using CRM.Common;
    using CRM.Model;
         /// <summary>
        /// 负责每个数据表的操作
       /// </summary>
    public partial class sysPermissListServices:BaseServices<CRM.Model.sysPermissList>,IsysPermissListServices
    {
    #region   定义构造函数， 接收autofac 将数据仓储层具体实现类的对象注入到此类中 
            
               IsysPermissListRepository dal; 
    
                public sysPermissListServices( IsysPermissListRepository dal)
           
        {
                this.dal = dal;
                base.baseDal = dal; 
            
           }
    
    
       #endregion
    
    //  #region   针对 此表的 特殊操作 写在此处 
            
    //    /// <summary>
    //    /// 负责用户权限按钮进行数据缓存操作，以及以后直接从缓存中使用
    //    /// </summary>
    //    /// <param name="userid"></param>
    //    /// <returns></returns>
    //            public List<CRM.Model.Usp_GetFunctionsForUser15_Result> GetFuctionsForUserByCache(int userid)
    //            {
    //                //注意： 缓存中的key 一定是每个用户有一个，彼此不重复
    //                string cachekey = Keys.PermissFuctionsForUser + userid;
    //               //1.0 从缓存中 根据户用获取其权限数据 
    //                object data = CacheMgr.GetData<List<CRM.Model.Usp_GetFunctionsForUser15_Result>>(cachekey);
    //                if (data == null)
    //                {
    //                    //从数据库获取一份权限按钮数据
    //                    var prmisslist = baseDal.RunProc<CRM.Model.Usp_GetFunctionsForUser15_Result> ("Usp_GetFunctionsForUser15" , userid);
    //                    // 将数据加入缓存 
    //                    CacheMgr.SetData(cachekey, prmisslist);
    //                    return prmisslist;
    //                }

    //                return data as List<CRM.Model.Usp_GetFunctionsForUser15_Result>;
    //            }
      // #endregion
    
             #region 针对此表的特殊操作写在此处

        /// <summary>
        /// 负责将用户权限按钮数据进行缓存操作，以及以后直接从缓存中获取
        /// </summary>
        /// <param name="userid"></param>
        /// <returns></returns>
        public List<Usp_GetFunctionsForUser15_Result>GetFuctionsForUserByCache (int userid)
        {
            //注意：缓存key一定是每个用户有一个，彼此不重复
            string cacheKey = Keys.PermissFuctionsForUser + userid;

            //1.0 从缓存中根据用户获取其权限按钮数据
            object data = CacheMgr.GetData<List<Usp_GetFunctionsForUser15_Result>>(cacheKey);
            if (data == null)
            {
                //从数据库获取一份权限按钮数据
                var prmisslist = baseDal.RunProc<Usp_GetFunctionsForUser15_Result>("Usp_GetFunctionsForUser15  "   +userid);
                //将数据加入缓存
                CacheMgr.SetData(cacheKey, prmisslist);

                return prmisslist;
            }

            return data as List<Usp_GetFunctionsForUser15_Result>;
        }

        #endregion
    }

 
}
