//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    using CRM.Model;
    using CRM.IRepository;
    
         /// <summary>
        /// 负责每个数据表的操作
       /// </summary>
    public partial class sysdiagramsRepository:BaseRepository<sysdiagrams>,IsysdiagramsRepository
    {
      #region   针对 此表的 特殊操作 写在此处 
            
            #endregion
    
    }
}
