//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Model.ModelViews
{
    using System;
    using System.Collections.Generic;
    
        using System.ComponentModel;
        using System.ComponentModel.DataAnnotations;
    public partial class sysMenusView
    {
     
        public int mID { get; set; }
        public int mParentID { get; set; }
        [DisplayName("菜单名称"), Required(ErrorMessage = "菜单名称非空")]
        public string mName { get; set; }
          [DisplayName("URL"), Required(ErrorMessage = "URL非空")]
        public string mUrl { get; set; }
          [DisplayName("区域"), Required(ErrorMessage = "区域非空")]
        public string mArea { get; set; }
          [DisplayName("控制器"), Required(ErrorMessage = "控制器非空")]
        public string mController { get; set; }
             [DisplayName("方法"), Required(ErrorMessage = "方法非空")]
        public string mAction { get; set; }
          [DisplayName("排序号"), Required(ErrorMessage = "排序号非空")]
        public int mSortid { get; set; }
        public int mStatus { get; set; }
         [DisplayName("菜单图标"), Required(ErrorMessage = "菜单图标非空")]
        public string mPicname { get; set; }
        public int mLevel { get; set; }
        public string mExp1 { get; set; }
        public Nullable<int> mExp2 { get; set; }
        public int mCreatorID { get; set; }
        public System.DateTime mCreateTime { get; set; }
        public Nullable<int> mUpdateID { get; set; }
        public System.DateTime mUpdateTime { get; set; }
    
        public virtual ICollection<sysFunctionView> sysFunction { get; set; }
        public virtual ICollection<sysPermissListView> sysPermissList { get; set; }
    }
}
